import Foundation

/// Agent status buckets reported by herdr snapshots and status events.
public enum AgentStatus: String, Codable, Sendable, CaseIterable {
    case idle
    case working
    case blocked
    case done
    case unknown

    public init(wire: String?) {
        self = AgentStatus(rawValue: wire ?? "unknown") ?? .unknown
    }

    /// Console sort bucket, matching Heeler: Blocked > Done > Working > Idle > Unknown.
    public var sortBucket: Int {
        switch self {
        case .blocked: return 0
        case .done: return 1
        case .working: return 2
        case .idle: return 3
        case .unknown: return 4
        }
    }
}

public struct AgentInfo: Codable, Sendable, Identifiable, Equatable {
    public let terminalID: String?
    /// Missing while herdr is still detecting the agent in a freshly started pane.
    public let agentKindRaw: String?
    /// herdr's agent name (`agent.rename`). Distinct from the kind in `agent`.
    public let name: String?
    /// Optional custom title from the wire (`title`), not the OSC terminal title.
    public let customTitle: String?
    public let terminalTitle: String?
    public let terminalTitleStripped: String?
    public let agentStatusRaw: String?
    public let workspaceID: String
    public let tabID: String
    public let paneID: String
    public let focused: Bool?
    public let cwd: String?
    public let revision: Int?
    /// herdr's resolved session reference for the agent (`agent_session`),
    /// e.g. the Atomic/Pi JSONL transcript path reported by the state hook.
    public let agentSession: AgentSessionRef?

    public var id: String { paneID }
    public var status: AgentStatus { AgentStatus(wire: agentStatusRaw) }
    /// Absolute path of the agent's session transcript when herdr reports one.
    public var agentSessionPath: String? {
        guard let agentSession, agentSession.kind == "path",
              let value = agentSession.value, !value.isEmpty
        else { return nil }
        return value
    }
    public var agent: String { agentKindRaw ?? "agent" }
    /// Sidebar / titlebar label without a tab label. Prefer `title(tabLabel:)`.
    public var title: String { title(tabLabel: nil) }

    public func updatingStatus(_ status: AgentStatus) -> AgentInfo {
        AgentInfo(
            terminalID: terminalID,
            agentKindRaw: agentKindRaw,
            name: name,
            customTitle: customTitle,
            terminalTitle: terminalTitle,
            terminalTitleStripped: terminalTitleStripped,
            agentStatusRaw: status.rawValue,
            workspaceID: workspaceID,
            tabID: tabID,
            paneID: paneID,
            focused: focused,
            cwd: cwd,
            revision: revision,
            // Upstream's status-only rebuild predates the fork's transcript
            // reference; dropping it here would blank `agentSessionPath` on
            // every status transition and stall the Atomic transcript reader.
            agentSession: agentSession
        )
    }

    /// Sidebar / titlebar label.
    ///
    /// `agent.rename` only accepts `[a-z][a-z0-9_-]{0,31}` so Chinese display
    /// names have to live on the tab (`tab.rename`). User-assigned tab labels
    /// win; then custom herdr names; then conversation OSC titles; generic OSC
    /// titles (kind, cwd basename) fall through to the herdr name, then kind.
    public func title(tabLabel: String?) -> String {
        Self.resolvedTitle(
            customTitle: customTitle,
            tabLabel: tabLabel,
            terminalTitle: terminalTitleStripped ?? terminalTitle,
            name: name,
            agentKind: agent,
            cwd: cwd
        )
    }

    public static func resolvedTitle(
        customTitle: String?,
        tabLabel: String? = nil,
        terminalTitle: String?,
        name: String?,
        agentKind: String,
        cwd: String?
    ) -> String {
        if let customTitle, !customTitle.isEmpty { return customTitle }
        if let tabLabel, !isGenericTabLabel(tabLabel, agentKind: agentKind, name: name) {
            return tabLabel
        }
        if let name, !name.isEmpty, !isAutoGeneratedName(name, agentKind: agentKind) {
            return name
        }
        if let terminalTitle, !isGenericTerminalTitle(terminalTitle, agentKind: agentKind, cwd: cwd) {
            return terminalTitle
        }
        if let name, !name.isEmpty { return name }
        return agentKind
    }

    /// New Agent sets the tab label to the kind (`agy`, `codex`, …).
    public static func isGenericTabLabel(_ label: String, agentKind: String, name: String?) -> Bool {
        let trimmed = label.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmed.isEmpty { return true }
        if trimmed.caseInsensitiveCompare(agentKind) == .orderedSame { return true }
        if let name, !name.isEmpty, trimmed == name, isAutoGeneratedName(name, agentKind: agentKind) {
            return true
        }
        return false
    }

    /// `agent.start` uses the kind, then `kind-` plus four hex chars on collision.
    public static func isAutoGeneratedName(_ name: String, agentKind: String) -> Bool {
        let trimmed = name.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmed.caseInsensitiveCompare(agentKind) == .orderedSame { return true }
        let prefix = agentKind + "-"
        guard trimmed.lowercased().hasPrefix(prefix.lowercased()) else { return false }
        let suffix = trimmed.dropFirst(prefix.count)
        return suffix.count == 4 && suffix.allSatisfy(\.isHexDigit)
    }

    public static func isGenericTerminalTitle(_ title: String, agentKind: String, cwd: String?) -> Bool {
        let trimmed = title.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmed.isEmpty { return true }
        if trimmed.caseInsensitiveCompare(agentKind) == .orderedSame { return true }
        guard let cwd, !cwd.isEmpty else { return false }
        if trimmed == cwd { return true }
        let base = URL(fileURLWithPath: cwd).lastPathComponent
        guard !base.isEmpty else { return false }
        if trimmed == base { return true }
        let stem: String
        if trimmed.hasSuffix("...") {
            stem = String(trimmed.dropLast(3))
        } else if trimmed.hasSuffix("…") {
            stem = String(trimmed.dropLast())
        } else {
            return false
        }
        return !stem.isEmpty && base.hasPrefix(stem)
    }

    enum CodingKeys: String, CodingKey {
        case terminalID = "terminal_id"
        case agentKindRaw = "agent"
        case name
        case customTitle = "title"
        case terminalTitle = "terminal_title"
        case terminalTitleStripped = "terminal_title_stripped"
        case agentStatusRaw = "agent_status"
        case workspaceID = "workspace_id"
        case tabID = "tab_id"
        case paneID = "pane_id"
        case focused
        case cwd
        case revision
        case agentSession = "agent_session"
    }
}

/// `agent_session` on the wire: `{"agent":"pi","kind":"path","source":"herdr:pi","value":"…jsonl"}`.
public struct AgentSessionRef: Codable, Sendable, Equatable {
    public let agent: String?
    public let kind: String?
    public let source: String?
    public let value: String?

    public init(agent: String?, kind: String?, source: String?, value: String?) {
        self.agent = agent
        self.kind = kind
        self.source = source
        self.value = value
    }
}
